### ISSUE TITLE
Model not working

### ISSUE THREAD

**Issue by sjehan** [sjehan/JupyterNotebooksFinetuning#7]
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    load_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

config = LoraConfig(
    r=16,
    lora_alpha=32,

<1 sec
ValueError: Target modules ['query_key_value'] not found in the base model. Please check the target modules and try again.

**Comment by AI-General** [comment]
Please try this:

https://github.com/sjehan/JupyterNotebooksFinetuning/blob/hongyuxiao/phi1.5_training.ipynb

This is full parameter fine-tuning.
